### ISSUE TITLE
Internal error when parameter is not included in an event

### ISSUE THREAD

**Issue by thom463s** [vopwn55/powerlang-issues#15]
Having no parameters (or arguments) inside an event will cause it to throw an internal error.
![image](https://github.com/user-attachments/assets/afeb12ae-2f5b-4a15-b867-dacabdb267bd)
![image](https://github.com/user-attachments/assets/12083e57-e13d-46e5-80b8-65f39e28ec7d)

This bug can currently be circumvented by adding a filler parameter instead.
![image](https://github.com/user-attachments/assets/9c85e785-1f3a-4db7-9133-413b3caaadd3)

**Comment by vopwn55** [comment]
Noted.

**Comment by vopwn55** [comment]
![image](https://github.com/user-attachments/assets/840312b5-f91c-42a4-be02-e8ae850fc565)
I cannot replicate this using neither example. Do you have any particular code snippet I can copy?

**Comment by thom463s** [comment]
You probably ended up fixing it along the way tbh.

**Comment by vopwn55** [comment]
I'm going to close this.
