### ISSUE TITLE
Setting the property of something to a variable truncates the variable's last character

### ISSUE THREAD

**Issue by Paracosm-Daemon** [vopwn55/powerlang-issues#17]
Self-explanatory.

Repro code:

![image](https://github.com/user-attachments/assets/39b12400-a8a5-4fa9-a142-cdd59ebbc106)

Compiled code:

![image](https://github.com/user-attachments/assets/43cb462a-59b5-4b94-8ed6-76b58cbb5bfe)

**Comment by vopwn55** [comment]
I am able to reproduce it. I will take a look.

**Comment by vopwn55** [comment]
Dev note: This is not a bug with Powerlang (presumably) but with the VisualSource library.

**Comment by Paracosm-Daemon** [comment]
> This is not a bug with Powerlang (presumably) but with the VisualSource library.

Strange! I remember fixing this by simply adding a semicolon to the end of that erroring line; do those matter when compiling to VisualSource? It seems so arbitrary

**Comment by vopwn55** [comment]
> Strange! I remember fixing this by simply adding a semicolon to the end of that erroring line; do those matter when compiling to VisualSource? It seems so arbitrary

They don't, but if adding a semicolon fixes the issue, it's really weird. Upon compiling the repro code attached in the original post, Powerlang correctly detects the variable as "label_text" and inputs the exact same entry into both blocks (as evident by the raw VisualSource dump I have created). However, it seems that RetroStudio is not entirely happy with this and messes it up.

**Comment by vopwn55** [comment]
Hi @Paracosm-Daemon , I found a workaround.
If you get rid of the two `print()`s at the beginning, the program will compile as expected without this bug. It may be that VisualSource simply does not like newlines (which the credits text uses).

**Comment by Paracosm-Daemon** [comment]
Interesting! That would explain it. I'll keep that in mind for the future; perhaps it's an issue with encoding strings?

I am aware of creating newlines with CTRL + J, so it may be worth checking if a script that prints a string with newlines will cause a truncating error like this, and if it doesn't, then it could be an oversight in Powerlang

**Comment by vopwn55** [comment]
You're right, I'll have to take a closer look at it.
