### ISSUE TITLE
Documentation lacks global functions

### ISSUE THREAD

**Issue by Paracosm-Daemon** [vopwn55/powerlang-issues#19]
Mentioned in the thread, though for awareness purposes: the global library is not mentioned in the documentation.
Functions such as `tostring()` are not mentioned throughout the docs.

![image](https://github.com/user-attachments/assets/b1543bff-7a1a-4e0b-974e-e913c05f5193)

**Comment by vopwn55** [comment]
Noted. Thank you!

**Comment by vopwn55** [comment]
Complete. Let me know if something is missing.
https://vopwn55.gitbook.io/powerlang-docs/advanced-information/global-functions
