### ISSUE TITLE
(Enhancement) IDE text zooming, undo/redo keybinds, etc.

### ISSUE THREAD

**Issue by Paracosm-Daemon** [vopwn55/powerlang-issues#21]
Though undoing and redoing _is_ in the IDE, being unable to control the undo history through CTRL+Z/CTRL+U (or CTRL+SHIFT+Z, unless these history keybinds can be controlled through SHIFT itself rather than CTRL) can be a miniscule but frustrating time-loss, especially given small qualms with holding CTRL and left/right shift or backspace.

When editing, I tend to quickly select or modify code with the CTRL key, though the IDE does not handle this very well:

https://github.com/user-attachments/assets/93a57512-25cc-41fa-ba84-c6643a426785

Eventually, this also leads to cases where I may use the CTRL + BACKSPACE functionality to delete a bulk of letters at once, but this causes issues:

https://github.com/user-attachments/assets/b953d867-75c1-4660-ab32-c2ec3d3d75cd

This, mixed with the lack of shortcuts for undoing can cause the workflow to be interrupted often.

Shortcuts aside, the lack of text zooming can also be an issue. I have a large monitor, thus I tend to zoom in text to make things easier to read, given I am nearsighted. Here is a comparison between the IDE and my Studio settings:

IDE:
![image](https://github.com/user-attachments/assets/2e39964c-ea18-4c95-be12-f60302b8caf5)

Studio:
![image](https://github.com/user-attachments/assets/3cfb5f15-015d-4bf1-a606-83a97916cbd4)

**Comment by vopwn55** [comment]
You bring up very good points Paracosm-Daemon.

> When editing, I tend to quickly select or modify code with the CTRL key, though the IDE does not handle this very well
The code box is just a native Roblox TextBox. Therefore I do not have control over how text is selected, unfortunately.

> Though undoing and redoing is in the IDE, being unable to control the undo history through CTRL+Z/CTRL+U (or CTRL+SHIFT+Z, unless these history keybinds can be controlled through SHIFT itself rather than CTRL) can be a miniscule but frustrating time-loss, especially given small qualms with holding CTRL and left/right shift or backspace.
You're right. I could add a Ctrl+Shift+Z / Ctrl+Shift+Y series of keybinds that will control undo/redo.

>Shortcuts aside, the lack of text zooming can also be an issue. I have a large monitor, thus I tend to zoom in text to make things easier to read, given I am nearsighted. Here is a comparison between the IDE and my Studio settings
Unfortunately it's not possible for the IDE to retrieve Studio settings due to the font setting being inaccessible. However I can add zoom in and zoom out buttons (and likely respective shortcuts, such as Ctrl+Shift++).

**Comment by Paracosm-Daemon** [comment]
Thank you very much! It's unfortunate that shortcuts aren't available, but the addition of zooming makes it much better for me to work nonetheless.
