### ISSUE TITLE
Missing syntax highlighting for certain keywords

### ISSUE THREAD

**Issue by Paracosm-Daemon** [vopwn55/powerlang-issues#25]
For reference, I am comparing what I believe should have keyword syntax highlighting with Lua. Here is a list of what has keyword highlighting in Lua:
```lua
local
if
not
and
or
return
for
in
while
repeat
until
do
function
```

In Powerlang, here is what I believe is missing keyword coloring:
```css
event
function
return
```

For future note, `nil` currently has keyword highlighting, though it should also have boolean coloring. I believe it currently looks pink in my version off the IDE due to my differing color settings:

![image](https://github.com/user-attachments/assets/73d29b68-ad9b-4a44-b97b-60977eeccbb5)

![image](https://github.com/user-attachments/assets/a92b757a-defb-4db1-b973-e711bc2b76a0)

**Comment by vopwn55** [comment]
Fixed in 0.11.
![image](https://github.com/user-attachments/assets/0fcf08de-1b8d-4e77-ad04-a630224d13d9)
