### ISSUE TITLE
Text zoom issues: Resizing the IDE doesn't adjust the ScrollingFrame's CanvasSize, zoom doesn't save

### ISSUE THREAD

**Issue by Paracosm-Daemon** [vopwn55/powerlang-issues#26]
I noticed that I wasn't able to see the last line of my code while adjusting my zoom to fit my monitor. This is because the content size is not updated after resizing the IDE, only after updating the code:

https://github.com/user-attachments/assets/460f1f05-4191-49d6-9cba-074cb6df88c3

Alongside this, closing Roblox Studio and reopening the IDE shows that the text zoom does not save. I suspect `Plugin:SetSetting()` was overshadowed.

**Comment by vopwn55** [comment]
> I noticed that I wasn't able to see the last line of my code while adjusting my zoom to fit my monitor. This is because the content size is not updated after resizing the IDE, only after updating the code:

Content will now refresh on zoom in/out, causing the scrolling frame to get updated.

> Alongside this, closing Roblox Studio and reopening the IDE shows that the text zoom does not save. I suspect Plugin:SetSetting() was overshadowed.

Not anymore, now your zoom should remain whenever you exit and reload the IDE.
