### ISSUE TITLE
(Enhancement) Overwrite script feature

### ISSUE THREAD

**Issue by Paracosm-Daemon** [vopwn55/powerlang-issues#27]
Though this was discussed in Discord, I'm bringing it here with more reasoning:

When I'm iterating through scripts, such as updating UI elements as I have set up a framework for that, it can be especially slow to have to re-import the script, rename it, and re-parent its children. This is also particularly true if said script has its `Disabled` property changed. Here is an example of what I may do:

https://github.com/user-attachments/assets/9575ed54-dc54-42e8-a14a-1d43fa49ebc7

This makes my iteration process comparatively more than 5 seconds slower on most occasions, such as if I am changing the Disabled property to `true`. If I am making minor adjustments to my code, such as fixing a small typo or changing a value as such in the video, having to re-import and delete my old script can be a big issue.

Though the argument can be made that previous, working scripts could be replaced with newer code that is buggy, what I am proposing should not overwrite the script you have selected by default - you are always able to back up your previous script and clone it. This safety can disrupt my workflow greatly.

The least disruptive proposal I have is, when importing with Explorer Selection, there could be a prompt that asks if you would like to overwrite the currently selected script or insert the script under it. This simple prompt would shave a lot more time off of my iteration process and make it much easier to do small updates to code.

**Comment by vopwn55** [comment]
The problem with this, really, is the fact that I'd have to add a server-side script to create this behavior, while I was aiming for a client-only experience. But I will take this into consideration and maybe introduce overwriting in the new importer.

**Comment by vopwn55** [comment]
This is done in the new importer
