### ISSUE TITLE
"OS" functions should have their own library

### ISSUE THREAD

**Issue by Paracosm-Daemon** [vopwn55/powerlang-issues#29]
Currently, the `os.time()`, `os.date()`, and `os.clock()` functions are all declared within the retrostudio library. I believe that this should be changed, as they are not exclusive to RetroStudio or under a class which has these methods inaccessible within RetroStudio. I point out the latter due to [`workspace:GetServerTimeNow()`](https://create.roblox.com/docs/reference/engine/classes/Workspace#GetServerTimeNow) not being directly callable through workspace, rather it is its own individual block.

To avoid breaking compatibility, the `os` functions within the retrostudio library can simply be declared as deprecated. This means people are still able to write `retrostudio.OsClock()`, but are more incentivized to use `os.clock()` instead (much like the built-in library within Luau; consistency is always nice!).

**Comment by vopwn55** [comment]
Added.
![image](https://github.com/user-attachments/assets/fe1587f7-41af-4c4f-8dda-1a43da24a4cf)
![image](https://github.com/user-attachments/assets/686cff81-442d-41ff-93b3-ace95331a6dd)
