### ISSUE TITLE
, is not working

### ISSUE THREAD

**Issue by CoolTNTBoy** [vopwn55/powerlang-issues#30]
When I put a comma in the script, for like parenting and stuff like that it just comes out with an error, the image is the error.
<img width="327" alt="e" src="https://github.com/user-attachments/assets/b91969ba-53c7-42ac-80d5-d0f9f21480e7">

**Comment by Paracosm-Daemon** [comment]
Could you give a snippet of your code? Comma separation works for me

**Comment by vopwn55** [comment]
We're going to need more elaboration. Could you send the code that does this?
