### ISSUE TITLE
Importer Will Create Blocks With Corrupted Names That Can't Be Interacted With (Just Numbers)

### ISSUE THREAD

**Issue by SpeedySpot** [vopwn55/powerlang-issues#37]
My code when imported will feature some (not all) blocks that are just named a single number. Usually this is impossible to do, and clicking on it will break the scripting window. These are **evil** blocks .
![image](https://github.com/user-attachments/assets/cf3c3040-1298-449f-a5b4-d3f1fa253082)
![image](https://github.com/user-attachments/assets/4b37a0d0-7d97-4847-8f93-8fe4538f2341)

**Comment by vopwn55** [comment]
This should not be possible. Have you tampered with the code in any way? What version of Powerlang do you use?

**Comment by SpeedySpot** [comment]
Heya, sorry for the late response.
I am used Powerlang Beta 0.11.0 and have not tampered with the importer or the plugin. This error is in the same script as issue #36 where it calls a function that doesn't exist (if that might help).

**Comment by vopwn55** [comment]
Cannot reproduce, please reopen in a new issue if this occurs again
