### ISSUE TITLE
RetroCompress always fails, with any given script

### ISSUE THREAD

**Issue by BobTrollge** [vopwn55/powerlang-issues#9]
![screenie](https://github.com/user-attachments/assets/8441580e-afda-43d3-994f-8ddb6473f17b)

Scripts fail to compile, giving the same error, no matter what source is given.

**Comment by BobTrollge** [comment]
The full error is
```
user_IDEPlugin.rbxmx.IDEPlugin.Powerlang.PowerlangCore.VisualLibrary.Version2.RetroCompress:39: attempt to perform arithmetic (mod) on nil and number
```

**Comment by vopwn55** [comment]
Hi, I am unable to reproduce this bug (using the latest version of both Roblox Studio and PowerIDE).
![image](https://github.com/user-attachments/assets/ebbf8cbf-21e5-4f48-98d4-3eb5a1c64938)
Tested on:
- OS: Arch Linux, Studio Version: 647
- OS: Windows 11, Studio Version: 647
- OS: Windows 11, Studio Version: 646

Are you using a modified IDEPlugin.rbxm file, or is there a specific script that you use that gives you an error?
